api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  formats:
    json: ["application/json"]
    html: ["text/html"]
  collection:
    pagination:
      page_parameter_name: page
      items_per_page_parameter_name: itemsPerPage 
  

