nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
    paths:
      "^/":
        origin_regex: true
        allow_origin: ["*"]
        allow_headers:
          ["X-Custom-Auth", "Content-Type", "Access-Control-Allow-Origin"]
        allow_methods: ["POST", "PUT", "GET", "DELETE"]
        max_age: 3600
