controllers:
  resource: ../src/Controller/
  type: attribute
authentication_token:
  path: /authentication_token
  methods: ["POST"]
mail:
  path: /mail
  methods: ["POST"]
add_image:
  path: /add_image
  methods: ["POST"]